packages:
  - packages/*
  - apps/*

overrides:
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  diff@<4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  happy-dom@<20.0.0: '>=20.0.0'
  js-yaml@<3.14.2: '>=3.14.2'
  qs@<6.14.1: '>=6.14.1'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
